### ISSUE TITLE
Package throws errors when building with scons

### ISSUE THREAD

**Issue by Andi24** [micolous/s2-geometry-library#4]
After configuring the gflags dependency, I ran the scons and the scons install commands and that threw two errors 

```
s2-geometry-library git:(master) sudo scons install
scons: Reading SConscript files ...

scons: warning: Two different environments were specified for target base/int128.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>

scons: warning: Two different environments were specified for target base/logging.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>

scons: warning: Two different environments were specified for target base/stringprintf.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>

scons: warning: Two different environments were specified for target base/strtoint.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>

scons: warning: Two different environments were specified for target strings/ascii_ctype.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>

scons: warning: Two different environments were specified for target strings/split.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>

scons: warning: Two different environments were specified for target strings/stringprintf.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>

scons: warning: Two different environments were specified for target strings/strutil.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>

scons: warning: Two different environments were specified for target util/coding/coder.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>

scons: warning: Two different environments were specified for target util/coding/varint.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>

scons: warning: Two different environments were specified for target util/hash/hash.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>

scons: warning: Two different environments were specified for target util/math/mathutil.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>

scons: warning: Two different environments were specified for target util/math/mathlimits.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>

scons: warning: Two different environments were specified for target util/math/exactfloat/exactfloat.os,
	but they appear to have the same action: $SHCXX -o $TARGET -c $SHCXXFLAGS $SHCCFLAGS $_CCCOMCOM $SOURCES
File "/Users/andreimasca/Documents/Workspace/backend/s2-geometry-library/geometry/SConstruct", line 67, in <module>
scons: done reading SConscript files.
scons: Building targets ...
g++ -o geometry/strings/split.os -c -fPIC -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DS2_USE_EXACTFLOAT -DHASH_NAMESPACE=std -std=c++11 -Igeometry -Igeometry/s2 -I/opt/local/include geometry/strings/split.cc
In file included from geometry/strings/split.cc:11:
In file included from geometry/base/strtoint.h:38:
In file included from geometry/base/basictypes.h:68:
geometry/base/docid.h:164:19: error: explicit specialization of non-template
      struct 'hash'
template<> struct hash<DocId> {
                  ^   ~~~~~~~
geometry/base/docid.h:284:19: error: explicit specialization of non-template
      struct 'hash'
template<> struct hash<DocId32Bit> {
                  ^   ~~~~~~~~~~~~
In file included from geometry/strings/split.cc:12:
In file included from geometry/strings/split.h:24:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ext/hash_map:212:5: warning:
      Use of the header <ext/hash_map> is deprecated. Migrate to
      <unordered_map> [-W#warnings]
#   warning Use of the header <ext/hash_map> is deprecated.  Migrate t...
    ^
In file included from geometry/strings/split.cc:12:
In file included from geometry/strings/split.h:31:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ext/hash_set:205:5: warning:
      Use of the header <ext/hash_set> is deprecated. Migrate to
      <unordered_set> [-W#warnings]
#   warning Use of the header <ext/hash_set> is deprecated.  Migrate t...
    ^
2 warnings and 2 errors generated.
scons: *** [geometry/strings/split.os] Error 1
scons: building terminated because of errors.
```

**Comment by Andi24** [comment]
Any help would be extremely useful as we're looking to creating a python version of this repo (https://github.com/awslabs/dynamodb-geo) and we need a python version of the s2 library.

**Comment by micolous** [comment]
Can you please tell me what version of g++ you're using? `g++ --version`

I suspect that your compiler doesn't support C++11.

Also what version of OSX and Xcode are you using?

The warnings at the top I haven't figureed out, and are to be expected for now.

**Comment by Andi24** [comment]
g++ --version output

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

Mac Version: Yosemite 10.10.5
Xcode version: Version 7.2 (7C68)

**Comment by Andi24** [comment]
I've done some research on your suggestion that my compiler doesn't support g++ 11, but all sources seem to be saying that xcode after a certain version supports it (and the one I have is far newer than the ones mentioned, i.e. 4.x)

**Comment by micolous** [comment]
OK, I can build this with an older version of clang (OSX 10.9, LLVM 5.1, clang 503.0.40), so this is quite strange.  I'm not sure what to make of this, but I'll need to try reproducing on 10.10, which I don't have installed.

**Comment by micolous** [comment]
I'm unable to install OSX 10.10 on my machine (the installation fails, it requires a repartition, repartitioning hangs for hours), so I don't have a way to reliably reproduce this in order to sort this out easily.

I've tried building this on a Linux system with clang-3.7 (which is the same as what you're running), and this builds successfully.

There's some issue with c++11 being selected in your compiler. You're right that it definitely should support it.

Unfortunately because I don't have a way to reproduce the environment, I don't know where to start on fixing it.

I don't think OSX support is strictly needed for the use case you're looking at, it sounds like the library is supposed to sit between the application and the data storage layer.  In which case, the application would probably be running in a virtualised Linux environment, where it does build reliably.  After all, the other library has a Java layer which is talked to from an iOS application, even though you can't use Java on iOS.

I notice that there's an issue with [libgflags on Ubuntu Wily, so avoid that](https://bugs.launchpad.net/ubuntu/+source/gflags/+bug/1469483).

**Comment by kvhooreb** [comment]
I'm using OSX 10.11 and had the same error. My C++ is (very) rusty and I'm just happy I got it to work, but I think the problem is related to this: http://stackoverflow.com/questions/6301966/c-nested-template-classes-error-explicit-specialization-in-non-namespace-sco

Both parts of the code that cause the errors seem to specify the same functionality for different Classes, on which the same function is called. So, in `docid.h`, I changed lines 164 - 168 (that cause the first error) from this:
```c++
template<> struct hash<DocId> {
  size_t operator()(const DocId& d) const {
    return static_cast<size_t>(d.docid());
  }
};
```
to this:

```c++
template<class T> struct hash {
  size_t operator()(const T& d) const {
    return static_cast<size_t>(d.docid());
  }
};
```
And I commented out the lines that cause the second error (284-286).
After a shitload of warnings, having to install swig, it installed correctly and seems to work.

**Comment by micolous** [comment]
Awesome, thanks!  So it wasn't what I thought.  I'm still a bit confused about why it worked on clang on Linux but not clang on OSX.  I'll pull that into the repository after a bit more testing.

The warnings are because I'm doing nasty/evil things with scons.  There's `libs2cellid` and `libs2` which each link a bunch of the same support code.

I think I'll need to do some major refactoring of the support code into a library in order to get this to behave.  Many of the functions are a snapshot of parts of Google's (internal) C++ standard library, which have been dumped into the original developers' source dump.  Some of this can be replaced by standard C++ library functions these days.

That's a longer term goal. Getting the library _actually building_ and working relatively well has been my first goal.  The patch you supply goes a step towards that for OSX users.

Thanks again. :+1:

**Comment by Andi24** [comment]
Great stuff guys, thanks so much! I wasn't very keen on peeking into the code myself, so I really appreciate the effort. Looking forward to the merge!

**Comment by micolous** [comment]
This appears to build correctly on Travis CI on OSX 10.11, so I think this is now resolved. Feel free to poke if there are more problems.

https://travis-ci.org/micolous/s2-geometry-library/jobs/102558771

**Comment by Andi24** [comment]
Just to confirm, it builds fine now, thanks a lot! :)

**Comment by micolous** [comment]
No problems, thanks for closing the loop. :)
